"""Re-export from castle-core for backward compatibility."""

from castle_core.manifest import *  # noqa: F401, F403
from castle_core.manifest import (  # noqa: F401 — explicit re-exports for type checkers
    BuildSpec,
    CaddySpec,
    Capability,
    CommandsSpec,
    DefaultsSpec,
    EnvMap,
    ExposeSpec,
    HttpExposeSpec,
    HttpInternal,
    HttpPublic,
    JobSpec,
    ManageSpec,
    ProgramSpec,
    ProxySpec,
    ReadinessHttpGet,
    RestartPolicy,
    RunBase,
    RunCommand,
    RunCompose,
    RunContainer,
    RunNode,
    RunPython,
    RunRemote,
    RunSpec,
    ServiceSpec,
    SystemdSpec,
    TLSMode,
)
